HEIG-Boom/heigvd-pro-a-02-SiTR

pom.xml
src/main/java/ch/heigvd/sitr/App.java
src/main/java/ch/heigvd/sitr/Vehicle.java
src/main/java/ch/heigvd/sitr/gui/SettingsWindow.form
src/main/java/ch/heigvd/sitr/gui/SettingsWindow.java
src/test/java/ch/heigvd/sitr/AppTest.java
src/test/java/ch/heigvd/sitr/VehicleTest.java

SiTR -> sitr
Viewer -> gui
Fixes #24

Renamed packages to follow standards

---

README.md
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java
src/main/java/ch/heigvd/sitr/vehicle/VehicleController.java
src/test/java/ch/heigvd/sitr/vehicle/VehicleControllerTest.java
src/test/java/ch/heigvd/sitr/vehicle/VehicleTest.java

Created vehicle package

---

src/main/java/ch/heigvd/sitr/vehicle/VehicleFactory.java
src/test/java/ch/heigvd/sitr/vehicle/VehicleFactoryTest.java

Created vehicle factory

---

src/main/java/ch/heigvd/sitr/model/ScenarioType.java
src/main/java/ch/heigvd/sitr/model/Simulation.java
src/main/java/ch/heigvd/sitr/model/VehicleBehaviourType.java
src/main/java/ch/heigvd/sitr/model/VehicleControllerType.java
src/test/java/ch/heigvd/sitr/model/ScenarioTypeTest.java
src/test/java/ch/heigvd/sitr/model/SimulationTest.java
src/test/java/ch/heigvd/sitr/model/VehicleBehaviourTypeTest.java
src/test/java/ch/heigvd/sitr/model/VehicleControllerTypeTest.java

This is a work in progress but I'd like to discuss some points here.
1. Maybe methods like `getControlerNames` should be in `VehicleControllerType`?
2. Should we put `kmhToMps()` and `mpsToKmh` in `Simulation`?
3. Should we continue with enums for VehicleBehaviours and Scenarios?
References #40 #54 and #65
Closes #65, closes #40.

Start of overarching model

---

src/main/java/ch/heigvd/sitr/gui/settings/SettingsWindow.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimulationWindow.java

Switching across windows and preserve settings window

---

src/main/java/ch/heigvd/sitr/gui/settings/SettingsPanel.java

Closes #83, Closes #81, Closes #82

Settings windows works with the differents enum types

---

config/vehicleController/reckless.xml
config/vehicleController/vehicleController.dtd
pom.xml
src/main/java/ch/heigvd/sitr/vehicle/VehicleController.java
src/main/resources/vehicleController/careful.xml
src/main/resources/vehicleController/reckless.xml
src/main/resources/vehicleController/timid.xml
src/test/java/ch/heigvd/sitr/vehicle/VehicleControllerTest.java
src/test/resources/vehicleController/careful.xml
src/test/resources/vehicleController/reckless.xml
src/test/resources/vehicleController/timid.xml

/!\ **dtd have been removed**, it seems giving xml path to dtd is difficult inside a jar /!\ 
- Pom.xml now copies resources to jar,
- Pom.xml now includes println in target/surfirereports (was helpful to have exception in a report)

Deploying jar with config files

---

src/main/java/ch/heigvd/sitr/App.java
src/main/java/ch/heigvd/sitr/model/ScenarioType.java
src/main/java/ch/heigvd/sitr/model/Simulation.java
src/main/java/ch/heigvd/sitr/model/VehicleBehaviourType.java
src/main/java/ch/heigvd/sitr/model/VehicleControllerType.java
src/test/java/ch/heigvd/sitr/model/ScenarioTypeTest.java
src/test/java/ch/heigvd/sitr/model/VehicleBehaviourTypeTest.java
src/test/java/ch/heigvd/sitr/model/VehicleControllerTypeTest.java

More natural enum representation, french gui

---

src/main/java/ch/heigvd/sitr/gui/settings/SettingsPanel.java
src/main/java/ch/heigvd/sitr/gui/settings/SettingsWindow.java

Getters for settings are OP

---

pom.xml
src/main/java/ch/heigvd/sitr/map/input/OpenDriveHandler.java
src/main/java/ch/heigvd/sitr/map/input/OpenDriveUnmarshaller.java
src/main/java/ch/heigvd/sitr/model/Simulation.java

I think that it fixes #113 
Could someone check that it has really been fixed ?

Jar packaging

---

src/main/java/ch/heigvd/sitr/gui/simulation/SimControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimulationWindow.java

Implementation of setters for the statistics label

---

src/main/java/ch/heigvd/sitr/gui/simulation/CarControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/MapPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimulationWindow.java
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java
src/main/java/ch/heigvd/sitr/vehicle/VehicleRenderer.java

Clickable car implemented according to Observer pattern

---

pom.xml
src/main/java/ch/heigvd/sitr/gui/simulation/SimulationWindow.java
src/main/java/ch/heigvd/sitr/utils/AccelerationNoise.java
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java
src/main/java/ch/heigvd/sitr/vehicle/VehicleController.java
src/main/resources/vehicle/regular.xml
src/main/resources/vehicle/truck.xml
src/main/resources/vehicleController/autonomous.xml
src/main/resources/vehicleController/careful.xml
src/main/resources/vehicleController/reckless.xml
src/main/resources/vehicleController/timid.xml
src/test/java/ch/heigvd/sitr/utils/AccelerationNoiseTest.java
src/test/java/ch/heigvd/sitr/vehicle/VehicleControllerTest.java
src/test/java/ch/heigvd/sitr/vehicle/VehicleTest.java
src/test/resources/vehicle/regular.xml
src/test/resources/vehicleController/autonomous.xml
src/test/resources/vehicleController/careful.xml
src/test/resources/vehicleController/reckless.xml
src/test/resources/vehicleController/timid.xml

Add white noise on vehicles accleration to simulate human driving

Stochastic model

---

src/main/java/ch/heigvd/sitr/model/Simulation.java
src/main/java/ch/heigvd/sitr/model/VehicleControllerType.java
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java
src/main/java/ch/heigvd/sitr/vehicle/VehicleController.java
src/main/java/ch/heigvd/sitr/vehicle/VehicleRenderer.java

Vehicles now have a `color` attribute, which is set by default to a default color stored in the `VehicleController` enum.
I also replaced `equals` and `hashcode` in `VehicleController` with lombok generated ones. Those are probably safer than our own.
Closes #69

Added a bit of color in our gloom world

---

src/main/java/ch/heigvd/sitr/gui/simulation/SimControlPanel.java
src/main/java/ch/heigvd/sitr/model/Simulation.java
src/main/java/ch/heigvd/sitr/model/VehicleControllerType.java

Fixes #141 by changing the pause mechanism.
We now cancel the timer and create a new one each time.

Fix bug where acceleration would build up during pause

---

src/main/java/ch/heigvd/sitr/gui/simulation/CarControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/MapPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimControlPanel.java
src/main/java/ch/heigvd/sitr/model/Simulation.java
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java

Actually, the panel allow the user to change the controller (and implicitely the color) of the selected vehicle. Great news, the Car Control Panel (CCP) doesn't flash the window anymore when enable/disable it.

[TOREVIEW] Car control panel can modify the vehicle

---

src/main/java/ch/heigvd/sitr/gui/simulation/CarControlPanel.java
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java

Fb refactor ccp

---

src/main/java/ch/heigvd/sitr/gui/simulation/SimControlPanel.java

SCP offers a stats generator button, correction of label

---

src/main/java/ch/heigvd/sitr/gui/simulation/CarControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/SimulationWindow.java
src/main/java/ch/heigvd/sitr/model/Simulation.java
src/main/java/ch/heigvd/sitr/model/VehicleBehaviour.java
src/main/java/ch/heigvd/sitr/statistics/Statistics.java
src/main/java/ch/heigvd/sitr/vehicle/Vehicle.java
statistics/GeneralStatistics.csv
statistics/vehicles/20190515230325446.csv

PR to fix X-Brast's mess.
Added statistics, integrated with GUI, and file generation.
Closes #125, closes #140

Statistics implemented

---

src/main/java/ch/heigvd/sitr/gui/settings/SettingsPanel.java
src/main/java/ch/heigvd/sitr/model/Scenario.java

Sim takes into account the maximum number of vehicles

---

README.md
src/main/java/ch/heigvd/sitr/model/Scenario.java
src/main/java/ch/heigvd/sitr/utils/Renderable.java
src/main/java/ch/heigvd/sitr/vehicle/VehicleRenderer.java

Cleaned up and changed scale and max number of vehicles for the Ring Road scenario.
#162

Cleanup model, vehicle and utils packages

---

src/main/java/ch/heigvd/sitr/gui/settings/SettingsWindow.java
src/main/java/ch/heigvd/sitr/gui/simulation/CarControlPanel.java
src/main/java/ch/heigvd/sitr/gui/simulation/MapPanel.java

all files from GUI package are ```CTRL + ALT + L```
#162

Reformat code for GUI Files
